<?php

/**
 * This is the model base class for the table "{{teachers2phd}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Teachers2phd".
 *
 * Columns in table "{{teachers2phd}}" available as properties of the model,
 * followed by relations of table "{{teachers2phd}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $teacher_id
 * @property integer $phd_level
 * @property string $phd_since
 *
 * @property Teachers2departments $teacher
 */
abstract class BaseTeachers2phd extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{teachers2phd}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Teachers2phd|Teachers2phds', $n);
	}

	public static function representingColumn() {
		return 'phd_since';
	}

	public function rules() {
		return array(
			array('teacher_id', 'required'),
			array('teacher_id, phd_level', 'numerical', 'integerOnly'=>true),
			array('phd_since', 'safe'),
			array('phd_level, phd_since', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, teacher_id, phd_level, phd_since', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'teacher' => array(self::BELONGS_TO, 'Teachers2departments', 'teacher_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'teacher_id' => null,
			'phd_level' => Yii::t('app', 'Phd Level'),
			'phd_since' => Yii::t('app', 'Phd Since'),
			'teacher' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('teacher_id', $this->teacher_id);
		$criteria->compare('phd_level', $this->phd_level);
		$criteria->compare('phd_since', $this->phd_since, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}